export const countries = [
  // "albania",
  // "andorra",
  // "armenia",
  // "australia",
  // "austria",
  // "azerbaijan",
  // "belarus",
  // "belgium",
  // "bosnia and herzegovina",
  // "bulgaria",
  // "croatia",
  // "cyprus",
  // "czech republic",
  // "denmark",
  // "estonia",
  // "finland",
  // "france",
  // "germany",
  // "georgia",
  // "greece",
  // "hungary",
  // "iceland",
  // "ireland",
  // "israel",
  // "italy",
  // "latvia",
  // "lithuania",
  // "luxembourg",
  // "macedonia",
  // "malta",
  // "moldova",
  // "monaco",
  // "montenegro",
  // "morocco",
  // "netherlands",
  // "norway",
  // "poland",
  // "portugal",
  // "romania",
  // "russia",
  // "san marino",
  // "serbia",
  // "slovenia",
  // "slovakia",
  // "spain",
  // "sweden",
  // "switzerland",
  // "turkey",
  // "ukraine",
  // "united kingdom",
  // "yugoslavia",
  "cyprus2016",
  "macedonia2008",
  "russia2017",
  "norway2005",
  "spain2005",
  "belgium2009",
  "belarus2011",
  "cyprus2007",
  "spain2004",
  "georgia2007",
  "cyprus2014",
  "macedonia2019",
  "latvia2010",
  "italy2014",
  "serbia2019",
  "armenia2014",
  "ukraine2018",
  "macedonia2018",
  "croatia2003",
  "slovenia2015",
  "russia2012",
];

export const countryNameMap = {
  // albania: "Albania",
  // andorra: "Andorra",
  // armenia: "Armenia",
  // australia: "Australia",
  // austria: "Austria",
  // azerbaijan: "Azerbaijan",
  // belarus: "Belarus",
  // belgium: "Belgium",
  // "bosnia and herzegovina": "Bosnia & Herzegovina",
  // bulgaria: "Bulgaria",
  // croatia: "Croatia",
  // cyprus: "Cyprus",
  // "czech republic": "Czech Republic",
  // denmark: "Denmark",
  // estonia: "Estonia",
  // finland: "Finland",
  // france: "France",
  // germany: "Germany",
  // georgia: "Georgia",
  // greece: "Greece",
  // hungary: "Hungary",
  // iceland: "Iceland",
  // ireland: "Ireland",
  // israel: "Israel",
  // italy: "Italy",
  // latvia: "Latvia",
  // lithuania: "Lithuania",
  // luxembourg: "Luxembourg",
  // macedonia: "North Macedonia",
  // malta: "Malta",
  // moldova: "Moldova",
  // monaco: "Monaco",
  // montenegro: "Montenegro",
  // morocco: "Morocco",
  // netherlands: "The Netherlands",
  // norway: "Norway",
  // poland: "Poland",
  // portugal: "Portugal",
  // romania: "Romania",
  // russia: "Russia",
  // "san marino": "San Marino",
  // serbia: "Serbia",
  // slovenia: "Slovenia",
  // slovakia: "Slovakia",
  // spain: "Spain",
  // sweden: "Sweden",
  // switzerland: "Switzerland",
  // turkey: "Turkey",
  // ukraine: "Ukraine",
  // "united kingdom": "United Kingdom",
  // yugoslavia: "Yugoslavia",
  cyprus2016: "Cyprus (2016)",
  macedonia2008: "FYR Macedonia (2008)",
  russia2017: "Russia (2017)",
  norway2005: "Norway (2005)",
  spain2005: "Spain (2005)",
  belgium2009: "Belgium (2009)",
  belarus2011: "Belarus (2011)",
  cyprus2007: "Cyprus (2007)",
  spain2004: "Spain (2004)",
  georgia2007: "Georgia (2007)",
  cyprus2014: "Cyprus (2014)",
  macedonia2019: "North Macedonia (2019)",
  latvia2010: "Latvia (2010)",
  italy2014: "Italy (2014)",
  serbia2019: "Serbia (2019)",
  armenia2014: "Armenia (2014)",
  ukraine2018: "Ukraine (2018)",
  macedonia2018: "FYR Macedonia (2018)",
  croatia2003: "Croatia (2003)",
  slovenia2015: "Slovenia (2015)",
  russia2012: "Russia (2012)",
};

export const countryFlagMap = {
  // turkey: "turkey.png",
  // "bosnia and herzegovina": "bosnia-and-herzegovina.png",
  // sweden: "sweden.png",
  // armenia: "armenia.png",
  // malta: "malta.png",
  // israel: "israel.png",
  // portugal: "portugal.png",
  // romania: "romania.png",
  // iceland: "iceland.png",
  // macedonia: "macedonia.png",
  // montenegro: "montenegro.png",
  // finland: "finland.png",
  // belarus: "belarus.png",
  // switzerland: "switzerland.png",
  // andorra: "andorra.png",
  // bulgaria: "bulgaria.png",
  // belgium: "belgium.png",
  // "czech republic": "czech-republic.png",
  // serbia: "serbia.png",
  // moldova: "moldova.png",
  // croatia: "croatia.png",
  // ireland: "ireland.png",
  // latvia: "latvia.png",
  // poland: "poland.png",
  // norway: "norway.png",
  // cyprus: "cyprus.png",
  // slovakia: "slovakia.png",
  // denmark: "denmark.png",
  // slovenia: "slovenia.png",
  // hungary: "hungary.png",
  // azerbaijan: "azerbaijan.png",
  // greece: "greece.png",
  // lithuania: "lithuania.png",
  // albania: "albania.png",
  // ukraine: "ukraine.png",
  // estonia: "estonia.png",
  // netherlands: "netherlands.png",
  // "united kingdom": "united-kingdom.png",
  // france: "france.png",
  // germany: "germany.png",
  // russia: "russia.png",
  // spain: "spain.png",
  // yugoslavia: "yugoslavia.png",
  // luxembourg: "luxembourg.png",
  // italy: "italy.png",
  // austria: "austria.png",
  // monaco: "monaco.png",
  // "san marino": "san-marino.png",
  // australia: "australia.png",
  // georgia: "georgia.png",
  // morocco: "morocco.png",
  cyprus2016: "cyprus.png",
  macedonia2008: "macedonia.png",
  russia2017: "russia.png",
  norway2005: "norway.png",
  spain2005: "spain.png",
  belgium2009: "belgium.png",
  belarus2011: "belarus.png",
  cyprus2007: "cyprus.png",
  spain2004: "spain.png",
  georgia2007: "georgia.png",
  cyprus2014: "cyprus.png",
  macedonia2019: "macedonia.png",
  latvia2010: "latvia.png",
  italy2014: "italy.png",
  serbia2019: "serbia.png",
  armenia2014: "armenia.png",
  ukraine2018: "ukraine.png",
  macedonia2018: "macedonia.png",
  croatia2003: "croatia.png",
  slovenia2015: "slovenia.png",
  russia2012: "russia.png",
};

export const rankToPointsMap = {
  1: 12,
  2: 10,
  3: 8,
  4: 7,
  5: 6,
  6: 5,
  7: 4,
  8: 3,
  9: 2,
  10: 1,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
};

export const all_voters = [
  //"Aivis",
  "Alex",
  //"Cecilia",
  "Costa",
  "Ed",
  //"Eirik",
  //"Hlynur",
  "Lukáš",
  "Luke",
  //"Maria",
  "Marko",
  "Matteo",
  "Miki",
  "Nathan",
  "Oliver",
  "Pedro",
  "Philip",
  "Rinor",
  //"Rita",
  "Rodrigo",
  "Simon",
  "Thomas",
  //"Tommy",
  //"Victoria",
  "Vladan",
  "Wiv",
];

export const audioMap = {
  swe09: "nf-pc-2/swe09.mp3",
  fra18: "nf-pc-2/fra18.mp3",
  nor19: "nf-pc-2/nor19.mp3",
  spa08: "nf-pc-2/spa08.mp3",
  swi13: "nf-pc-2/swi13.mp3",
  fin13: "nf-pc-2/fin13.mp3",
  swe04: "nf-pc-2/swe04.mp3",
  slo19: "nf-pc-2/slo19.mp3",
  mac15: "nf-pc-2/mac15.mp3",
  nor18: "nf-pc-2/nor18.mp3",
  swe11: "nf-pc-2/swe11.mp3",
  ice15: "nf-pc-2/ice15.mp3",
  ser07: "nf-pc-2/ser07.mp3",
  swe10: "nf-pc-2/swe10.mp3",
  ger08: "nf-pc-2/ger08.mp3",
  sam06: "nf-pc-2/sam06.mp3",
  alb20: "nf-pc-2/alb20.mp3",
  ice12a: "nf-pc-2/ice12a.mp3",
  mol20: "nf-pc-2/mol20.mp3",
};

export const magic_code = "loveunlimited";

export const currentEdition = "4";

export default countries;
