export const countries = [
  // "albania",
  // "andorra",
  // "armenia",
  // "australia",
  // "austria",
  // "azerbaijan",
  // "belarus",
  // "belgium",
  // "bosnia and herzegovina",
  // "bulgaria",
  // "croatia",
  // "cyprus",
  // "czech republic",
  // "denmark",
  // "estonia",
  // "finland",
  // "france",
  // "germany",
  // "georgia",
  // "greece",
  // "hungary",
  // "iceland",
  // "ireland",
  // "israel",
  // "italy",
  // "latvia",
  // "lithuania",
  // "luxembourg",
  // "macedonia",
  // "malta",
  // "moldova",
  // "monaco",
  // "montenegro",
  // "morocco",
  // "netherlands",
  // "norway",
  // "poland",
  // "portugal",
  // "romania",
  // "russia",
  // "san marino",
  // "serbia",
  // "slovenia",
  // "slovakia",
  // "spain",
  // "sweden",
  // "switzerland",
  // "turkey",
  // "ukraine",
  // "united kingdom",
  // "yugoslavia",
  "switzerland2014",
  "croatia2010",
  "portugal2018",
  "france2016",
  "estonia2012",
  "greece1985",
  "spain2014",
  "germany2012",
  "montenegro2013",
  "norway2014",
  "belgium2010",
  "sweden2014",
  "spain2007",
  "croatia2020",
  "france2020",
  "switzerland1988",
  "albania2018",
  "spain1991",
  "israel2010",
  "poland2014",
  "ukraine2013",
  "andorra2007",
  "serbia2012",
];

export const countryNameMap = {
  // albania: "Albania",
  // andorra: "Andorra",
  // armenia: "Armenia",
  // australia: "Australia",
  // austria: "Austria",
  // azerbaijan: "Azerbaijan",
  // belarus: "Belarus",
  // belgium: "Belgium",
  // "bosnia and herzegovina": "Bosnia & Herzegovina",
  // bulgaria: "Bulgaria",
  // croatia: "Croatia",
  // cyprus: "Cyprus",
  // "czech republic": "Czech Republic",
  // denmark: "Denmark",
  // estonia: "Estonia",
  // finland: "Finland",
  // france: "France",
  // germany: "Germany",
  // georgia: "Georgia",
  // greece: "Greece",
  // hungary: "Hungary",
  // iceland: "Iceland",
  // ireland: "Ireland",
  // israel: "Israel",
  // italy: "Italy",
  // latvia: "Latvia",
  // lithuania: "Lithuania",
  // luxembourg: "Luxembourg",
  // macedonia: "North Macedonia",
  // malta: "Malta",
  // moldova: "Moldova",
  // monaco: "Monaco",
  // montenegro: "Montenegro",
  // morocco: "Morocco",
  // netherlands: "The Netherlands",
  // norway: "Norway",
  // poland: "Poland",
  // portugal: "Portugal",
  // romania: "Romania",
  // russia: "Russia",
  // "san marino": "San Marino",
  // serbia: "Serbia",
  // slovenia: "Slovenia",
  // slovakia: "Slovakia",
  // spain: "Spain",
  // sweden: "Sweden",
  // switzerland: "Switzerland",
  // turkey: "Turkey",
  // ukraine: "Ukraine",
  // "united kingdom": "United Kingdom",
  // yugoslavia: "Yugoslavia",
  switzerland2014: "Switzerland (2014) [Simon & Philip]",
  croatia2010: "Croatia (2010) [Marko]",
  portugal2018: "Portugal (2018) [Costa]",
  france2016: "France (2016) [Rodrigo]",
  estonia2012: "Estonia (2012) [Pedro]",
  greece1985: "Greece (1985) [Philip]",
  spain2014: "Spain (2014) [Nathan]",
  germany2012: "Germany (2012) [Vladan]",
  montenegro2013: "Montenegro (2013) [Oliver]",
  norway2014: "Norway (2014) [Costa]",
  belgium2010: "Belgium (2010) [Rodrigo]",
  sweden2014: "Sweden (2014) [Thomas]",
  spain2007: "Spain (2007) [Luke]",
  croatia2020: "Croatia (2020) [Marko]",
  france2020: "France (2020) [Pedro]",
  switzerland1988: "Switzerland (1988) [Thomas]",
  albania2018: "Albania (2018) [Oliver]",
  spain1991: "Spain (1991) [Wiv]",
  israel2010: "Israel (2010) [Vladan]",
  poland2014: "Poland (2014) [Simon]",
  ukraine2013: "Ukraine (2013) [Luke]",
  andorra2007: "Andorra (2007) [Nathan]",
  serbia2012: "Serbia (2012) [Wiv]",
};

export const countryFlagMap = {
  // turkey: "turkey.png",
  // "bosnia and herzegovina": "bosnia-and-herzegovina.png",
  // sweden: "sweden.png",
  // armenia: "armenia.png",
  // malta: "malta.png",
  // israel: "israel.png",
  // portugal: "portugal.png",
  // romania: "romania.png",
  // iceland: "iceland.png",
  // macedonia: "macedonia.png",
  // montenegro: "montenegro.png",
  // finland: "finland.png",
  // belarus: "belarus.png",
  // switzerland: "switzerland.png",
  // andorra: "andorra.png",
  // bulgaria: "bulgaria.png",
  // belgium: "belgium.png",
  // "czech republic": "czech-republic.png",
  // serbia: "serbia.png",
  // moldova: "moldova.png",
  // croatia: "croatia.png",
  // ireland: "ireland.png",
  // latvia: "latvia.png",
  // poland: "poland.png",
  // norway: "norway.png",
  // cyprus: "cyprus.png",
  // slovakia: "slovakia.png",
  // denmark: "denmark.png",
  // slovenia: "slovenia.png",
  // hungary: "hungary.png",
  // azerbaijan: "azerbaijan.png",
  // greece: "greece.png",
  // lithuania: "lithuania.png",
  // albania: "albania.png",
  // ukraine: "ukraine.png",
  // estonia: "estonia.png",
  // netherlands: "netherlands.png",
  // "united kingdom": "united-kingdom.png",
  // france: "france.png",
  // germany: "germany.png",
  // russia: "russia.png",
  // spain: "spain.png",
  // yugoslavia: "yugoslavia.png",
  // luxembourg: "luxembourg.png",
  // italy: "italy.png",
  // austria: "austria.png",
  // monaco: "monaco.png",
  // "san marino": "san-marino.png",
  // australia: "australia.png",
  // georgia: "georgia.png",
  // morocco: "morocco.png",
  switzerland2014: "switzerland.png",
  croatia2010: "croatia.png",
  portugal2018: "portugal.png",
  france2016: "france.png",
  estonia2012: "estonia.png",
  greece1985: "greece.png",
  spain2014: "spain.png",
  germany2012: "germany.png",
  montenegro2013: "montenegro.png",
  norway2014: "norway.png",
  belgium2010: "belgium.png",
  sweden2014: "sweden.png",
  spain2007: "spain.png",
  croatia2020: "croatia.png",
  france2020: "france.png",
  switzerland1988: "switzerland.png",
  albania2018: "albania.png",
  spain1991: "spain.png",
  israel2010: "israel.png",
  poland2014: "poland.png",
  ukraine2013: "ukraine.png",
  andorra2007: "andorra.png",
  serbia2012: "serbia.png",
};

export const rankToPointsMap = {
  1: 12,
  2: 10,
  3: 8,
  4: 7,
  5: 6,
  6: 5,
  7: 4,
  8: 3,
  9: 2,
  10: 1,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
};

export const all_voters = [
  //"Aivis",
  "Alex",
  //"Cecilia",
  "Costa",
  "Ed",
  //"Eirik",
  //"Hlynur",
  "Lukáš",
  "Luke",
  //"Maria",
  "Marko",
  "Matteo",
  "Miki",
  "Nathan",
  "Oliver",
  "Pedro",
  "Philip",
  "Rinor",
  //"Rita",
  "Rodrigo",
  "Simon",
  "Thomas",
  //"Tommy",
  //"Victoria",
  "Vladan",
  "Wiv",
];

export const audioMap = {};

export const magic_code = "movetheworld";

export const currentEdition = "5";

export default countries;
