export const countries = [
  // "albania",
  // "andorra",
  // "armenia",
  // "australia",
  // "austria",
  // "azerbaijan",
  // "belarus",
  // "belgium",
  // "bosnia and herzegovina",
  // "bulgaria",
  // "croatia",
  // "cyprus",
  // "czech republic",
  // "denmark",
  // "estonia",
  // "finland",
  // "france",
  // "germany",
  // "georgia",
  // "greece",
  // "hungary",
  // "iceland",
  // "ireland",
  // "israel",
  // "italy",
  // "latvia",
  // "lithuania",
  // "luxembourg",
  // "macedonia",
  // "malta",
  // "moldova",
  // "monaco",
  // "montenegro",
  // "morocco",
  // "netherlands",
  // "norway",
  // "poland",
  // "portugal",
  // "romania",
  // "russia",
  // "san marino",
  // "serbia",
  // "slovenia",
  // "slovakia",
  // "spain",
  // "sweden",
  // "switzerland",
  // "turkey",
  // "ukraine",
  // "united kingdom",
  // "yugoslavia",
  "time",
"lost_in_a_dance",
"energy",
"nii_kõrgele",
"tartu",
"sunday_night",
"kaos",
"6",
"the_lucky_one",
"alabama_watchdog",
"magus_melanhoolia",
"heaven's_not_that_far_tonight",
  "i_love_you",
"hurt",
"play",
"sinä_päivänä_kun_kaikki_rakastaa_mua",
"lie",
"dark_side",
"kelle_mä_soitan",
  "world_on_fire",
"hero",
"who_i_am",
"my_lonely_voice",
"let_loose",
"witch_woods",
"fallen_angel",
"feel_again",
"eyes_wide_open",
"i_can't_escape",
"monument",
"faith_bloody_faith",
];

export const countryNameMap = {
  // albania: "Albania",
  // andorra: "Andorra",
  // armenia: "Armenia",
  // australia: "Australia",
  // austria: "Austria",
  // azerbaijan: "Azerbaijan",
  // belarus: "Belarus",
  // belgium: "Belgium",
  // "bosnia and herzegovina": "Bosnia & Herzegovina",
  // bulgaria: "Bulgaria",
  // croatia: "Croatia",
  // cyprus: "Cyprus",
  // "czech republic": "Czech Republic",
  // denmark: "Denmark",
  // estonia: "Estonia",
  // finland: "Finland",
  // france: "France",
  // germany: "Germany",
  // georgia: "Georgia",
  // greece: "Greece",
  // hungary: "Hungary",
  // iceland: "Iceland",
  // ireland: "Ireland",
  // israel: "Israel",
  // italy: "Italy",
  // latvia: "Latvia",
  // lithuania: "Lithuania",
  // luxembourg: "Luxembourg",
  // macedonia: "North Macedonia",
  // malta: "Malta",
  // moldova: "Moldova",
  // monaco: "Monaco",
  // montenegro: "Montenegro",
  // morocco: "Morocco",
  // netherlands: "The Netherlands",
  // norway: "Norway",
  // poland: "Poland",
  // portugal: "Portugal",
  // romania: "Romania",
  // russia: "Russia",
  // "san marino": "San Marino",
  // serbia: "Serbia",
  // slovenia: "Slovenia",
  // slovakia: "Slovakia",
  // spain: "Spain",
  // sweden: "Sweden",
  // switzerland: "Switzerland",
  // turkey: "Turkey",
  // ukraine: "Ukraine",
  // "united kingdom": "United Kingdom",
  // yugoslavia: "Yugoslavia",
"time": "Time",
"lost_in_a_dance": "Lost in a Dance",
"energy": "Energy",
"nii_kõrgele": "Nii kõrgele",
"tartu": "Tartu",
"sunday_night": "Sunday Night",
"kaos": "Kaos",
"6": "6",
"the_lucky_one": "The Lucky One",
"alabama_watchdog": "Alabama Watchdog",
"magus_melanhoolia": "Magus melanhoolia",
"heaven's_not_that_far_tonight": "Heaven's Not That Far Tonight",
  "i_love_you": "I Love You",
"hurt": "Hurt",
"play": "Play",
"sinä_päivänä_kun_kaikki_rakastaa_mua": "Sinä päivänä kun kaikki rakastaa mua",
"lie": "Lie",
"dark_side": "Dark Side",
"kelle_mä_soitan": "Kelle mä soitan",
  "world_on_fire": "World on Fire",
"hero": "Hero",
"who_i_am": "Who I Am",
"my_lonely_voice": "My Lonely Voice",
"let_loose": "Let Loose",
"witch_woods": "Witch Woods",
"fallen_angel": "Fallen Angel",
"feel_again": "Feel Again",
"eyes_wide_open": "Eyes Wide Open",
"i_can't_escape": "I Can't Escape",
"monument": "Monument",
"faith_bloody_faith": "Faith Bloody Faith",
};

export const countryFlagMap = {
  // turkey: "turkey.png",
  // "bosnia and herzegovina": "bosnia-and-herzegovina.png",
  // sweden: "sweden.png",
  // armenia: "armenia.png",
  // malta: "malta.png",
  // israel: "israel.png",
  // portugal: "portugal.png",
  // romania: "romania.png",
  // iceland: "iceland.png",
  // macedonia: "macedonia.png",
  // montenegro: "montenegro.png",
  // finland: "finland.png",
  // belarus: "belarus.png",
  // switzerland: "switzerland.png",
  // andorra: "andorra.png",
  // bulgaria: "bulgaria.png",
  // belgium: "belgium.png",
  // "czech republic": "czech-republic.png",
  // serbia: "serbia.png",
  // moldova: "moldova.png",
  // croatia: "croatia.png",
  // ireland: "ireland.png",
  // latvia: "latvia.png",
  // poland: "poland.png",
  // norway: "norway.png",
  // cyprus: "cyprus.png",
  // slovakia: "slovakia.png",
  // denmark: "denmark.png",
  // slovenia: "slovenia.png",
  // hungary: "hungary.png",
  // azerbaijan: "azerbaijan.png",
  // greece: "greece.png",
  // lithuania: "lithuania.png",
  // albania: "albania.png",
  // ukraine: "ukraine.png",
  // estonia: "estonia.png",
  // netherlands: "netherlands.png",
  // "united kingdom": "united-kingdom.png",
  // france: "france.png",
  // germany: "germany.png",
  // russia: "russia.png",
  // spain: "spain.png",
  // yugoslavia: "yugoslavia.png",
  // luxembourg: "luxembourg.png",
  // italy: "italy.png",
  // austria: "austria.png",
  // monaco: "monaco.png",
  // "san marino": "san-marino.png",
  // australia: "australia.png",
  // georgia: "georgia.png",
"time": "estonia.png",
"lost_in_a_dance": "estonia.png",
"energy": "estonia.png",
"nii_kõrgele": "estonia.png",
"tartu": "estonia.png",
"sunday_night": "estonia.png",
"kaos": "estonia.png",
"6": "estonia.png",
"the_lucky_one": "estonia.png",
"alabama_watchdog": "estonia.png",
"magus_melanhoolia": "estonia.png",
"heaven's_not_that_far_tonight": "estonia.png",
  "i_love_you": "finland.png",
"hurt": "finland.png",
"play": "finland.png",
"sinä_päivänä_kun_kaikki_rakastaa_mua": "finland.png",
"lie": "finland.png",
"dark_side": "finland.png",
"kelle_mä_soitan": "finland.png",
  "world_on_fire": "norway.png",
"hero": "norway.png",
"who_i_am": "norway.png",
"my_lonely_voice": "norway.png",
"let_loose": "norway.png",
"witch_woods": "norway.png",
"fallen_angel": "norway.png",
"feel_again": "norway.png",
"eyes_wide_open": "norway.png",
"i_can't_escape": "norway.png",
"monument": "norway.png",
"faith_bloody_faith": "norway.png",
};

export const rankToPointsMap = {
  1: 12,
  2: 10,
  3: 8,
  4: 7,
  5: 6,
  6: 5,
  7: 4,
  8: 3,
  9: 2,
  10: 1,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
};

export const all_voters = [
  // "Aivis",
  // "Aleksandra",
  // "Alex",
  // "Cecilia",
  "Costa",
  // "Ed",
  // "Eirik",
  // "Hannah",
  // "Hlynur",
  // "Lukáš",
  "Luke",
  "Maria",
  "Marko",
  "Matteo",
  // "Michael",
  "Miki",
  "Nathan",
  "Nick",
  "Oliver",
  "Pedro",
  "Philip",
  "Rinor",
  // "Rita",
  "Rodrigo",
  "Simon",
  "Thomas",
  // "Tommy",
  // "Victoria",
  "Vladan",
  "Wiv",
];

export const audioMap = {};

export const magic_code = "raging";

export default countries;

export const currentEdition = "3";

const edition_map = {
  yugo: 10,
  east: 7,
  west: 6,
  south: 8,
  north: 9,
  raging: 11,
};

export function edition_id(edition_name = "") {
  return currentEdition;
  // console.log("Edition "+ edition_name)
  // if (edition_name === "") {
  //   edition_name = currentEdition;
  // }
  //
  // if (edition_name in edition_map) {
  //   return edition_map[edition_name];
  // }
  // return 0;
}

export const edition_list = {
  west: [
    "germany2003",
    "belgium2006",
    "ireland2011",
    "france2010",
    "hungary2011",
  ],
  east: [
    "belarus2019",
    "ukraine2010",
    "moldova2010",
    "bulgaria2012",
    "latvia2020",
  ],
  south: [
    "greece2009",
    "cyprus2012",
    "israel2015",
    "spain2009",
    "portugal2014",
  ],
  north: [
    "iceland2008",
    "denmark2007",
    "norway2019",
    "sweden2008",
    "finland2009",
  ],
  yugo: [
    "slovenia2006",
    "croatia2006",
    "bosnia2004",
    "serbia2020",
    "macedonia2006",
  ],
  raging: countries,
};

export function get_countries(edition_name = "") {
  if (edition_name === "") {
    edition_name = currentEdition;
  }

  if (edition_name in edition_list) {
    return edition_list[edition_name];
  }
  return countries;
}

export const num_of_qualifiers = 10;

const country_to_edition_map = {
  germany2003: "west",
  belgium2006: "west",
  ireland2011: "west",
  france2010: "west",
  hungary2011: "west",
  belarus2019: "east",
  ukraine2010: "east",
  moldova2010: "east",
  bulgaria2012: "east",
  latvia2020: "east",
  greece2009: "south",
  cyprus2012: "south",
  israel2015: "south",
  spain2009: "south",
  portugal2014: "south",
  iceland2008: "north",
  denmark2007: "north",
  norway2019: "north",
  sweden2008: "north",
  finland2009: "north",
  slovenia2006: "yugo",
  croatia2006: "yugo",
  bosnia2004: "yugo",
  serbia2020: "yugo",
  macedonia2006: "yugo",
};

export function get_edtion_for_country(country) {
  return country_to_edition_map[country];
}

export const videomap = {

  "i_will_love_again": "01.mp4",
  "nochenka": "02.mp4",
  "thinking": "03.mp4",
  "akoma_jo": "04.mp4",
  "ti_ho_voluto_bene_veramente": "05.mp4",
  "haide": "06.mp4",
  "me_gusta": "07.mp4",
  "superman": "08.mp4",
  "nobody's_wife": "09.mp4",
  "mr": "10.mp4",
  "brodolom": "11.mp4",
  "dancing_queen": "12.mp4",
  "rapide": "13.mp4",
  "i_drove_all_night": "14.mp4",
  "nemir": "15.mp4",
  "zaljuljali_smo_svijet": "16.mp4",
  "take_it_off": "17.mp4",
  "what_i": "18.mp4",
  "all_by_myself": "19.mp4",
  "şirket": "20.mp4",
  "okeani": "21.mp4",
  "te_despertare": "22.mp4",
  "bella_bella": "23.mp4",
}
